name: Execute Python Scripts on New Theme-YML Files

on:
  workflow_dispatch:
  push:
    paths:
      - 'themes/*'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Python3 requirements.txt
      run: |
        pip3 install -r requirements.txt
        echo 🏅

    - name: Generate json
      run: |
        python3 tools/generatJson.py
        echo 🏅

    - name: Generate json files
      run: |
        python3 tools/generateJsonFiles.py
        echo 🏅

    - name: Generate Installers
      run: |
        python3 tools/generateShFiles.py
        echo 🏅

    - name: update themes in gogh file
      run: |
        python3 tools/updateThemes.py
        echo 🏅

    - name: Git commit
      run: |
        git config user.name  github-actions[bot]
        git config user.email github-actions[bot]@github.com
        git add .
        git commit -m "------- Generate Themes -------"
        git push