name: Execute Python Scripts on New Theme-YML Files

on:
  workflow_dispatch:
  push:
    paths:
      - 'theme-yml/*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update ubuntu
      run: |
        sudo apt-get update
        echo 🏅

    - name: Install git
      run: |
        sudo apt-get install git -y
        echo 🏅

    - name: Install python3
      run: |
        sudo apt-get install python3 -y
        echo 🏅

    - name: Install pip3
      run: |
        sudo apt-get install -y python3-pip
        echo 🏅

    - name: Python3 requirements.txt
      run: |
        pip3 install -r requirements.txt
        echo 🏅

    - name: Generate json
      run: |
        python3 tools/generatJson.py
        echo 🏅

    - name: Generate Installers
      run: |
        python3 tools/generateShFiles.py
        echo 🏅

    - name: Git commit
      run: |
        git config user.name  github-actions[bot]
        git config user.email github-actions[bot]@github.com
        git add .
        git commit -m "------- Generate Themes -------"
        git push