name: Run Generators

on:
  workflow_dispatch:
  push:
    paths:
      - 'themes/*'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run python scripts
      run: |
        echo 🏅 - requirements.txt
        pip3 install -r requirements.txt

        echo 🏅 - Generate json
        python3 tools/pipe-generateJson.py

        echo 🏅 - Generate json files
        python3 tools/pipe-generateJsonFiles.py

        echo 🏅 - Generate Csv
        python3 tools/pipe-generateCsv.py

        echo 🏅 - Generate Installers
        python3 tools/pipe-generateShFiles.py

        echo 🏅 - update themes in gogh file
        python3 tools/pipe-updateThemes.py

        echo 🏅 - Pipeline run date
        python3 tools/pipe.py

    - name: Git commit
      run: |
        git config user.name  github-actions[bot]
        git config user.email github-actions[bot]@github.com
        git add .
        git commit -m "------- 🤖 Gogh 🤖 -------"
        git push